### ISSUE TITLE
Wrong versions

### ISSUE THREAD

**Issue by Futuraura** [omnixerio/devices-mod#53]
![image](https://user-images.githubusercontent.com/50999063/222946142-111bd857-af43-4dee-80ae-d3dc116cdd1f.png)
I think the latest tag should not be 0.5.0.1, but instead 5.5.1 because the last version was 5.5

**Comment by QboiDev** [comment]
Versions from 0.5.1 up to 0.6.0 are for mc1.19.2.
Versions 0.5.0 and 0.5.0.1 are for mc1.18.2.
The version 0.5.5 actually should be 0.6.4. The versions were messed up from the start.
Also, 0.5.0.1 is based on 0.5.0, not 0.5.5.

This is a one-time case of the versions being weird and all, since I couldn't find a better way to do it. We forgor to go to 0.6.x when porting to 1.19.2...

**Comment by QboiDev** [comment]
Will close this now.
